import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SideMenu from "@/components/ui/common/side-menu";
import { getDictionary, hasLocale } from "./dictionaries";
import "./globals.css";
import { notFound } from "next/dist/client/components/navigation";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipPopup } from "@base-ui/react";
import { TooltipProvider } from "@/components/ui/8bit/tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "es" }];
}

export default async function RootLayout({
  children,
  params,
}: LayoutProps<"/[lang]">) {
  const { lang } = await params;

  if (!hasLocale(lang)) {
    // If a user types an invalid language in the URL (e.g., /fr/...),
    // this instantly throws a Next.js 404 page instead of crashing your app.
    notFound();
  }

  const dictionary = await getDictionary(lang);

  return (
    <html
      lang={lang}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="flex flex-row w-full h-screen overflow-hidden">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <SideMenu dictionary={dictionary} lang={lang} />
            <main className="relative flex-1 h-full overflow-x-hidden overflow-y-auto">
              {children}
            </main>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
